### ISSUE TITLE
Stops after a certain time

### ISSUE THREAD

**Issue by futuretap** [alteral/xcmonkey#3]
In my tests, xcmonkey stops working after a certain time and just quits (exit code 0). The tested app continues to run.
Is this intentional? Can I increase the test duration?

**Comment by alteral** [comment]
Hi @futuretap, thanks for raising this!

You can use the `--duration` argument to control the duration of the test. The default value is `60sec`.

So executing this command will run the test for `100` seconds:

```bash
xcmonkey test --duration 100 --udid "413EA256-CFFB-4312-94A6-12592BEE4CBA" --bundle-id "com.app.example"
```

Run any command with `-h` argument to see all possible options, e.g.:

```bash
xcmonkey -h
xcmonkey test -h
```

**Comment by futuretap** [comment]
Thanks!
