### ISSUE TITLE
Error - 'idb' doesn't seem to be installed

### ISSUE THREAD

**Issue by lalkrishna** [alteral/xcmonkey#4]
I'm getting an error:

`'idb' doesn't seem to be installed`

I've installed idb using python3

`pip3.6 install fb-idb`

**Comment by alteral** [comment]
Hi @lalkrishna, thanks for giving xcmonkey a try! 🙂

Could you please attach an output of `which idb` command?

Ideally it should look something like this:

```bash
$ which idb 
/opt/homebrew/bin/idb
```

**Comment by alteral** [comment]
Hi @lalkrishna,

I'm closing this issue for now. Feel free to comment or reopen it if you're still having this type of error.

Best wishes,
Alex
