### ISSUE TITLE
Force being kept in app

### ISSUE THREAD

**Issue by futuretap** [alteral/xcmonkey#5]
There are many ways the user can leave the app (on MKMapView by following the Legal link, in SFSafariVC by tapping the Safari button, etc.). It would be great if such app switches could be detected and "reversed" by going back to the app. Otherwise xcmonkey effectively tests Safari or some other app, not our target app.

**Comment by alteral** [comment]
Hi Ortwin,
Thanks for opening the issue!

Great idea, will do my best to implement such an option soon 👍

Best wishes,
Alex

**Comment by alteral** [comment]
Hi @futuretap,

This feature is implemented in `v1.2.0` 🎉
If you have a moment to check it out, I'd really appreciate that.

Best wishes
Alex

**Comment by futuretap** [comment]
Works great, thanks.
